apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: backend
  name: backend
  namespace: my-demo-namespace
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      automountServiceAccountToken: false
      containers:
      - envFrom:
        - secretRef:
            name: backend-creds
            optional: false
        - configMapRef:
            name: cm-backend
            optional: false
        image: lvthillo/movie-backend
        imagePullPolicy: Always
        name: backend