apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: my-demo-namespace
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32001
