apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: my-demo-namespace
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32002
