apiVersion: v1
kind: Service
metadata:
  name: mongo-express-svc
  namespace: my-demo-namespace
spec:
  type: NodePort
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32000
