apiVersion: v1
data:
  ME_CONFIG_BASICAUTH_PASSWORD: dGVzdA==
  ME_CONFIG_BASICAUTH_USERNAME: dGVzdA==
  ME_CONFIG_MONGODB_ADMINPASSWORD: c2VjcmV0
  ME_CONFIG_MONGODB_ADMINUSERNAME: cm9vdC11c2Vy
kind: Secret
metadata:
  name: mongo-express-creds
  namespace: my-demo-namespace