apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongodb
  name: mongodb
  namespace: my-demo-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo
        name: mongodb
        envFrom:
          - secretRef:
              name: mongodb-creds
              optional: false
          - configMapRef:
              name: cm-mongodb
              optional: false
        imagePullPolicy: Always
        #livenessProbe:
        #  exec:
        #    command:
        #    - '"bash", "-c", "mongo -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD
        #      --eval db.adminCommand(''ping'')"'
        #  failureThreshold: 3
        #  initialDelaySeconds: 5
        #  periodSeconds: 3
        #  successThreshold: 1
        #  timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 150m
            memory: 256Mi